# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  encoding: unicode
  database: d9pg3k6n2ur84e
  pool: 5
  username: getwdprlalhplp
  password: BpIxJRThb5_OdKb24Xnx8PmVnk
  host: ec2-23-21-73-32.compute-1.amazonaws.com
  port: 5432


